split out split units finale

diff --git a/.github/workflows/conditional.yaml b/.github/workflows/conditional.yaml
--- a/.github/workflows/conditional.yaml
+++ b/.github/workflows/conditional.yaml
@@ -70,7 +70,18 @@ jobs:
         run: exit 2
 
   finale:
-    needs: [ units, split-units ]
+    needs: [ units ]
+    if: ${{ always() }} # Always run even if any "needs" jobs fail
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Fail if any previous failure
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
+      - name: Success otherwise
+        run: echo "Success!"
+
+  finale2:
+    needs: [ split-units ]
     if: ${{ always() }} # Always run even if any "needs" jobs fail
     runs-on: ubuntu-22.04
     steps:
